-- =============================================================
-- 03_tables.sql
-- Table definitions have moved to sql/tables/.
-- Each table is a separate file -- add new tables there.
-- This file is intentionally empty.
-- =============================================================
